#!/bin/sh
printf 'PUBLIC_SUPABASE_URL=%s\nPUBLIC_SUPABASE_ANON_KEY=%s\nPUBLIC_GA_MEASUREMENT_ID=%s\n' \
  "$PUBLIC_SUPABASE_URL" \
  "$PUBLIC_SUPABASE_ANON_KEY" \
  "$PUBLIC_GA_MEASUREMENT_ID" > .env
npm run build
